image: docker

stages:
  - test
  - build
  - deploy

test_job_crawler:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk update && apk upgrade
    - apk add python3-dev libffi-dev openssl-dev gcc libc-dev make
    - apk add --no-cache py-pip python3 
    - pip install --no-cache-dir docker-compose
  script:
    - docker-compose up -d
    - docker-compose ps
    - docker exec crawler /bin/sh -c "python3 -m unittest discover -s tests/ && coverage run -m unittest discover -s tests/ && coverage report --include crawler/crawler.py"
    - docker exec ui /bin/sh -c "cd .. && python -m unittest discover -s tests/ && coverage run -m unittest discover -s tests/ && coverage report --include ui/ui.py"

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t sm0ke87/search_engine_crawler:$CI_COMMIT_REF_SLUG ./search_engine_crawler
    - docker push sm0ke87/search_engine_crawler:$CI_COMMIT_REF_SLUG
    - docker build --pull -t sm0ke87/search_engine_ui:$CI_COMMIT_REF_SLUG ./search_engine_ui
    - docker push sm0ke87/search_engine_ui:$CI_COMMIT_REF_SLUG
    - docker build --pull -t sm0ke87/rabbitmq:$CI_COMMIT_REF_SLUG ./rabbitMQ
    - docker push sm0ke87/rabbitmq:$CI_COMMIT_REF_SLUG

deploy-prod:
  stage: deploy
  image: nekottyo/kustomize-kubeval:latest
  before_script:
    - apk add --no-cache git curl bash
    - git clone http://${CI_USERNAME}:${CI_TOKEN}@62.84.119.217//root/devops-2022-02_project.git
    - cd devops-2022-02_project
    - git init
    - git remote set-url origin http://${CI_USERNAME}:${CI_TOKEN}@62.84.119.217/root/devops-2022-02_project.git
    - git config --global user.email "gitlab@gitlab.com"
    - git config --global user.name "${CI_USERNAME}"
    - git config --get user.email
    - git config --get user.name
  script:
    - git checkout -B master1
    - cd kubernetes
    - kustomize edit set image sm0ke87/rabbitmq:main=sm0ke87/rabbitmq:${CI_COMMIT_SHORT_SHA}
    - kustomize edit set image sm0ke87/search_engine_crawler:main=sm0ke87/search_engine_crawler:${CI_COMMIT_SHORT_SHA}
    - kustomize edit set image sm0ke87/search_engine_ui:main=sm0ke87/search_engine_ui:${CI_COMMIT_SHORT_SHA}
    - cat kustomization.yaml
    - git commit -am '[skip ci] PROD image update'
    - git push origin master1

