version: '3.3'
services:
  mongo:
    image: mongo:3.2
    container_name: 'mongo'
    volumes:
      - post_db:/data/db
    networks:
      - back_net
    env_file:
      - .env

  rabbitmq:
    build: ./rabbitMQ
    container_name: 'rabbitmq'
    extra_hosts:
      - "staticrabbit:127.0.0.1"
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - back_net

  ui:
    depends_on:
      - "mongo"
    build: ./search_engine_ui
    image: ${USER_NAME}/search_engine_ui:${VERSION}
    container_name: 'ui'
    env_file:
      - .env
    ports:
      - ${PORT}:8000/tcp
    networks:
      - back_net
      - front_net
  
  crawler:
    depends_on:
      - "mongo"
      - "rabbitmq"
    build: ./search_engine_crawler
    image: ${USER_NAME}/search_engine_crawler:${VERSION}
    container_name: 'crawler'
    env_file:
      - .env
    networks:
      - back_net
      - front_net
  
  prometheus:
    build: ./monitoring/prometheus
    image: ${USER_NAME}/prometheus:${VERSION}
    container_name: 'prometheus'
    networks:
      - back_net
      - front_net
  
  grafana:
    build: ./monitoring/grafana
    image: ${USER_NAME}/grafana:${VERSION}
    container_name: 'grafana'
    networks:
      - back_net
      - front_net


volumes:
  post_db:

networks:
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
