apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./deployment.yml
images:
- name: sm0ke87/grafana:main
  newName: sm0ke87/grafana
  newTag: "25024870"
- name: sm0ke87/prometheus:main
  newName: sm0ke87/prometheus
  newTag: "25024870"
- name: sm0ke87/rabbitmq:main
  newName: sm0ke87/rabbitmq
  newTag: "25024870"
- name: sm0ke87/search_engine_crawler:main
  newName: sm0ke87/search_engine_crawler
  newTag: "25024870"
- name: sm0ke87/search_engine_ui:main
  newName: sm0ke87/search_engine_ui
  newTag: "25024870"

